T-M1B - CREATE SPI-GPIO CLASS IN QEMU
chen-iris/openbmc-qemu pull request #2
Opened 2022-06-07 00:47 UTC by chen-iris

[T122700039](https://www.internalfb.com/intern/tasks/?t=122700039)

2022-06-07 17:15 UTC, zhdaniel12 requested changes
I think about the name for this class, I think spi-gpio is better. Reason:
It is more explicit: telling this device is building up an SPI bus with GPIO pins.

2022-06-07 17:15 UTC, zhdaniel12 commented on hw/ssi/spi-bit-bang.c
> +    .parent         = TYPE_SYS_BUS_DEVICE,
As this "device" does not have MMIO or PIO, I think we need not base class with SYS_BUS_DEVICE. The simple SYS_BUS_DEVICE is good.

2022-06-07 22:06 UTC, zhdaniel12 commented on include/hw/ssi/spi_gpio.h
> +#define TYPE_SPI_GPIO "spi.gpio.flash"
spi_gpio is good, it does not related to flash. 
BTW, not sure what is the convention for the TPYE_SPI_GPIO mapping to real class name? "spi_gpio"?

2022-06-07 22:26 UTC, williamspatrick commented on hw/arm/aspeed_soc.c
> +    object_initialize_child(obj, "spigpio", &s->spi_gpio, typename);
nit: I think `spi-gpio` will fit the convention better here.

2022-06-07 22:26 UTC, williamspatrick commented on hw/arm/aspeed_soc.c
> +    object_initialize_child(obj, "spigpio", &s->spi_gpio, typename);
We appear to be reusing `typename = "aspeed.fmc-ast2600"`.  I don't think that's what you want.

2022-06-07 22:26 UTC, williamspatrick commented on hw/arm/aspeed_soc.c
> +    object_initialize_child(obj, "spigpio", &s->spi_gpio, typename);
I think this whole line (180) actually needs to be in the Yv3.5 section of the file somewhere.  This would add a `spi-gpio` block for every Aspeed 2600 system, which isn't what we want.

Probably in `static void fby35_i2c_init(AspeedMachineState *bmc)` in `aspeed.c`.  (I know that function is poorly named in this regard since we're not actually doing i2c-init but it is a sufficient place to put it for now that is unique to that system).

2022-06-07 22:26 UTC, williamspatrick commented on hw/ssi/spi_gpio.c
> +    .name           = "spi-gpio", // modify
Good.  I think this `.name` is what is suppose to match the 2nd parameter to `object_initialize_child` above.

2022-06-07 22:26 UTC, williamspatrick commented on include/hw/ssi/spi_gpio.h
> +#define TYPE_SPI_GPIO "spi.gpio.flash"
Isn't the convention that, if you have a `#define` like this that it also goes in `.name` above?

Looks like we've picked 3 different names for the same thing.  Probably should use the `TYPE_SPI_GPIO` everywhere.

2022-06-07 22:26 UTC, williamspatrick commented on include/hw/arm/aspeed_soc.h
> +    SpiGpioState spi_gpio;
As a starting point I think you should put this into the `AspeedMachineClass` instead of the `AspeedSocState`.  We may need to organize the machine-classes a little different in order to only put the spi-gpio on Yv35, but maybe it will be acceptable to have it as an extra pointer stored in the `AspeedMachineClass`.  I don't think here in the `AspeedSocState` is correct though.

2022-06-07 23:16 UTC, zhdaniel12 commented on hw/arm/aspeed_soc.c
> +    object_initialize_child(obj, "spigpio", &s->spi_gpio, typename);
yea, we have just discussed about this, Add the spi_gpio controller in machine (board) and init at machine level is the plan. Now the code is just to enable developing the core SPI line protocol logic. 

The overall design is:
1. Adding a new kconfig (CONFIG_SPI_GPIO), to introduce this new common feature (support bitbang SPI). An abstract class SpiGpio will be created to captures all the core logic of SPI line protocol encoding/decoding.
2. A concrete AspeedGpiosSpiPort class will be created to capture how to connect it to the gpio controller. 
3. Add AspeedGpioSpiPort in our own machine, so we need create a new MachineState.

2022-06-08 20:10 UTC, peterdelevoryas commented
I looked at how AspeedSMCState outputs to the M25P80, and here's basically what I think it should be:

- SpiGpioState needs to construct a spi bus member, and then you have to construct the M25P80 device on the spi bus.
- SpiGpioState needs to have input GPIO's that it initializes and connects to the Aspeed GPIO's that are selected in the device tree
- Also: I'm not sure how the chip-select pin should be handled, you might be able to just connect the Aspeed GPIO directly to the M25P80 chip-select and bypass the whole SpiGpio state, unless you actually need to listen to the value

```
struct SpiGpioState {
    DeviceState parent; // Probably needs to be a qdev

    SSIBus *spi;
    qemu_irq sck, miso, mosi;
};

static void sck_handler(void *opaque, int n, int level) {}
static void miso_handler(void *opaque, int n, int level) {}
static void mosi_handler(void *opaque, int n, int level) {}

// In spi_gpio_realize (I think):
s->spi = ssi_create_bus(DEVICE(s), "my-bus");
qdev_init_gpio_in_named(s, sck_handler, "sck", 1);
qdev_init_gpio_in_named(s, miso_handler, "miso", 1);
qdev_init_gpio_in_named(s, mosi_handler, "mosi", 1);
// Not sure how to get the qemu_irq from the input pin except like this:
s->sck = qdev_get_gpio_in_named(s, "sck", 0);
s->miso = qdev_get_gpio_in_named(s, "miso", 0);
s->mosi = qdev_get_gpio_in_named(s, "mosi", 0);
// I don't think this will work exactly, but hopefully something like this is right:
qdev_connect_gpio_out_named(aspeed_gpio, "gpioX3", 0, s->sck);
qdev_connect_gpio_out_named(aspeed_gpio, "gpioX4", 0, s->miso);
qdev_connect_gpio_out_named(aspeed_gpio, "gpioX5", 0, s->mosi);

// In the Fby35 machine initialization
DeviceState *sg = qdev_new("spi-gpio");
qdev_realize(sg, NULL, &error_fatal);

DeviceState *m25p80 = qdev_new("n25q256a");
qdev_realize(m25p80, BUS(sg->spi), &error_fatal);
qemu_irq m25p80_cs_line = qdev_get_gpio_in_named(m25p80, SSI_GPIO_CS, 0);
qdev_connect_gpio_out_named(aspeed_gpio, "gpioX0", 0, m25p80_cs_line);
```

Again, very rough idea, but something like this? We can try to figure out exactly how to connect the Aspeed GPIO's by stepping through the aspeed_gpio.c initialization of irq's in gdb.

@williamspatrick @zhdaniel12

2022-06-10 20:17 UTC, zhdaniel12 commented on hw/arm/aspeed.c
> +    qdev_connect_gpio_out_named(DEVICE(&bmc->soc.gpio),
miso shall not connected as gpio_out. This is SPI_GPIO's output pin, instead of GPIO device's output.
SPI_GPIO is a "virtual" slave SPI controller at device side.

2022-06-10 23:50 UTC, zhdaniel12 commented on include/hw/ssi/spi_gpio.h
> +    qemu_irq sck, miso, mosi, cs_line;
In my design guide is define bool attribute to save the latest state of the pin, the qemu_irq is not needed save in statee
```suggestion
       bool sck, miso, mosi, cs_line;
```

2022-06-11 00:02 UTC, zhdaniel12 commented on hw/arm/aspeed.c
> +                                "sysbus-irq", 185, spi_gpio->cs_line);
```suggestion
    qdev_connect_gpio_out_named(DEVICE(&bmc->soc.gpio),
                                "sysbus-irq", 185, 
                                qdev_get_gpio_in_named(m25p80, SSI_GPIO_CS_in, 0));
```
Also considering MACRO, which converting the GPIO name to this number.  i.e. AST_GPIO_2_IRQ_NUM('X', 0) 
This way the code will tell we connect GPIOX0 as SPI_GPIO_CS input for our device.
all the SPI_GPIO input pin connecting to bmc->soc.gpio code can follow this pattern.

2022-06-11 00:07 UTC, zhdaniel12 commented on hw/ssi/spi_gpio.c
> +static void mosi_handler(void *opaque, int n, int level) {}
here mosi_handler save the level to SpiGpioState::mosi, which will be used by the cs_line_handler

2022-06-11 00:10 UTC, zhdaniel12 commented on hw/ssi/spi_gpio.c
> +    qdev_init_gpio_in_named(dev, cs_line_handler, "cs_line", 1);
```suggestion
    qdev_init_gpio_in_named(dev, cs_line_handler, "SPI_CS_in", 1);
```

2022-06-11 00:13 UTC, zhdaniel12 commented on hw/ssi/spi_gpio.c
> +    s->miso = qdev_get_gpio_in_named(dev, "miso", 0);
```suggestion
    qdev_init_gpio_in_named(dev, cs_line_handler, "SPI_CS_in", 1);
    qdev_init_gpio_in_named(dev, sck_handler, "SPI_CLK", 1);
    qdev_init_gpio_in_named(dev, mosi_handler, "SPI_MOSI", 1);

     s->cs = 1;
     s->sck = 1;
     s->mosi = 1;
     s->miso = 1;
```

2022-06-11 00:19 UTC, zhdaniel12 commented on hw/ssi/spi_gpio.c
> +static void mosi_handler(void *opaque, int n, int level) {}
```suggestion
static void mosi_handler(void *opaque, int n, int level)
{
     SpiGpioState *s = SPI_GPIO(opaque);
     s->mosi = !!level;
}
```

2022-06-11 00:25 UTC, zhdaniel12 commented on hw/ssi/spi_gpio.c
> +static void sck_handler(void *opaque, int n, int level) {}
```suggestion
static void sck_handler(void *opaque, int n, int level) 
{
     SpiGpioState *s = SPI_GPIO(opaque);
     if ( s->cs ) /* cs# is high, not selected, do nothing*/
          return; 
     bool pre = s->clk;
     s->clk = !!level;
     bool cur = s->clk;
     if ( !pre && cur ) {
          return do_rising_edge();
      }
      if ( pre && !cur) {
            return do_falling_edge();
      }
      return; // no clk, do nothing.   
}
```

2022-06-11 02:32 UTC, chen-iris commented on hw/ssi/spi_gpio.c
> +static void sck_handler(void *opaque, int n, int level) {}
Thank you for this suggestion. I would like to address the implementation of these handlers in a different commit/PR so it isn't too cluttered so this will be incorporated in a future patch.

2022-06-13 15:52 UTC, zhdaniel12 commented on hw/ssi/spi_gpio.c
> +    qdev_init_gpio_in_named(dev, miso_handler, "SPI_MISO", 1);
you shall init "SPI_MISO" as output pin use qdev_init_gpio_out_named
Then connect aspeed_gpio's with it. 
```suggestion
    qdev_init_gpio_out_named(dev, s->miso_pin, "SPI_MISO", 1);
```

2022-06-13 15:53 UTC, zhdaniel12 commented on include/hw/ssi/spi_gpio.h
> +};
```suggestion
        qemu_irq miso_output_pin, cs_output_pin
};
```

2022-06-13 15:54 UTC, zhdaniel12 commented on hw/ssi/spi_gpio.c
> +}
```suggestion
```

2022-06-13 16:47 UTC, zhdaniel12 commented on hw/arm/aspeed.c
> +                             &error_abort);
```suggestion
    /* connect spi_gpio's output pin SPI_MISO to aspeed_gpio's GPIOX5 */
    qdev_connect_gpio_out_named(DEVICE(spi_gpio), "SPI_MISO", 0,  
        &bmc->soc.gpio.gpios[5][18]);  
```
howto get the qemu_irq reference of each GPIO pin of aspeed_gpio, we need discuss.

2022-06-13 18:35 UTC, zhdaniel12 commented on hw/arm/aspeed.c
> +                                qdev_get_gpio_in_named(m25p80, SSI_GPIO_CS, 0));
```suggestion
    /* connect aspeed_gpio GPIOX0 to SPI_GPIO's SPI_CS_in 
     * and connect SPI_GPIO's SPI_CS_out to w25p80's SSI_GPIO_CS
     */
    qdev_connect_gpio_out_named(DEVICE(&bmc->soc.gpio), "sysbus-irq", AST_GPIO_IRQ_X0_NUM,
                                qdev_get_gpio_in_named(spi_gpio, "SPI_CS_in", 0));
                                
    qdev_connect_gpio_out_named(DEVICE(spi_gpio), "SPI_CS_out", 0,
                                qdev_get_gpio_in_named(m25p80, "SSI_GPIO_CS", 0));
                               
```

2022-06-13 18:37 UTC, zhdaniel12 commented on hw/ssi/spi_gpio.c
> +    s->cs = !!level;
```suggestion
    s->cs = !!level;
    /* relay the CS to output spi_cs_out pin */
    qemu_set_irq(&s->cs_output_pin, s->cs);
```

2022-06-13 23:32 UTC, zhdaniel12 commented on hw/arm/aspeed.c
> +
I review the aspeed_gpio.c code, and noticed that it only expose each GPIO pins as
1. sysbus-irq[n] for used as output pin.
2. bool property named as "GPIO**" i.e. "GPIOX9" for used as input pin. 

Thus in SPI_GPIO object we need not model an output pin and connect to aspeed_gpio. 
instead we can directly push the output to aspeed_gpio using object_property_bool_set()

2022-06-13 23:41 UTC, zhdaniel12 commented on include/hw/ssi/spi_gpio.h
> +    qemu_irq miso_output_pin, cs_output_pin;
```suggestion
    qemu_irq cs_output_pin;
    AspeedGPIOState * aspeed_gpio;
```

2022-06-13 23:43 UTC, zhdaniel12 commented on hw/ssi/spi_gpio.c
> +    qdev_init_gpio_out_named(dev, &s->miso_output_pin, "SPI_MISO", 1);
```suggestion
    qdev_init_gpio_out_named(dev, &s->miso_output_pin, "SPI_MISO", 1);
```

2022-06-14 18:56 UTC, merged